### ISSUE TITLE
error in documentation...  reference to https://dashboad.heroku.com/

### ISSUE THREAD

**Issue by markmarino** [tonesto7/echo-speaks-server#34]
I was trying to follow the instructions to update the server here:

https://tonesto7.github.io/echo-speaks-docs/updates/server_update/

And it took me a while to figure out there is a typo in the Automated Method documentation for when you are instructed to go to https://dashboad.heroku.com/  and not https://dashboa**r**d.heroku.com/

If you go to the link in the documentation, you get browser security error and it's not obvious at all that there is a simply typo in the URL that is causing the issue.

**Comment by tonesto7** [comment]
thanks for reporting this will be resolved when I push out this weeks update
